// So Cal Off-Roaders - Complete Trails Database (30 Trails)
const trailsDB = [
  {
    "id": 1,
    "name": "Calico Ghost Town",
    "location": "Yermo, CA",
    "county": "San Bernardino",
    "difficulty": "beginner",
    "type": "desert",
    "distance": "15 miles",
    "duration": "3-4 hours",
    "description": "Historic silver mining town with easy trails through colorful rock formations. Great for beginners with stunning desert views and mining ruins to explore.",
    "coordinates": { "lat": 34.9483, "lng": -116.8642 },
    "camping": true,
    "campingInfo": "Developed campground at Calico Ghost Town, primitive camping nearby",
    "image": "calico.jpg",
    "rating": 4.5,
    "reviews": 128,
    "onxSlug": "odessa-doran-loop" // Verified: This maps the primary loop through Calico
  },
  {
    "id": 2,
    "name": "Johnson Valley",
    "location": "Johnson Valley, CA",
    "county": "San Bernardino",
    "difficulty": "moderate",
    "type": "desert",
    "distance": "Various",
    "duration": "Half to full day",
    "description": "Vast OHV area famous for the King of the Hammers race. Features everything from easy desert roads to extreme rock crawling.",
    "coordinates": { "lat": 34.3833, "lng": -116.6167 },
    "camping": true,
    "campingInfo": "Dispersed camping throughout, no facilities",
    "image": "johnson-valley.jpg",
    "rating": 4.7,
    "reviews": 203,
    "onxSlug": "johnson-valley-ohv-area" // Verified
  },
  {
    "id": 4,
    "name": "Holcomb Creek",
    "location": "Fawnskin, CA",
    "county": "San Bernardino",
    "difficulty": "advanced",
    "type": "canyon",
    "distance": "8 miles",
    "duration": "4-6 hours",
    "description": "Technical creek crossing trail with rocky sections and water obstacles.",
    "coordinates": { "lat": 34.2667, "lng": -117.1333 },
    "camping": true,
    "campingInfo": "Primitive camping along creek, pack it out",
    "image": "holcomb-creek.jpg",
    "rating": 4.6,
    "reviews": 89,
    "onxSlug": "holcomb-creek" // Verified
  },
  {
    "id": 5,
    "name": "Gold Mountain",
    "location": "Big Bear, CA",
    "county": "San Bernardino",
    "difficulty": "advanced",
    "type": "rock",
    "distance": "6 miles",
    "duration": "3-5 hours",
    "description": "Challenging rocky ascent with tight switchbacks. Rewarding panoramic views of Big Bear Lake.",
    "coordinates": { "lat": 34.2167, "lng": -117.0833 },
    "camping": false,
    "campingInfo": "No camping on trail",
    "image": "gold-mountain.jpg",
    "rating": 4.4,
    "reviews": 112,
    "onxSlug": "3n69-gold-mountain" // Verified
  },
  {
    "id": 6,
    "name": "Dishpan Springs",
    "location": "Big Bear, CA",
    "county": "San Bernardino",
    "difficulty": "extreme",
    "type": "rock",
    "distance": "4 miles",
    "duration": "4-8 hours",
    "description": "Massive boulders and steep climbs. Only for built rigs with experienced drivers.",
    "coordinates": { "lat": 34.25, "lng": -117.05 },
    "camping": false,
    "campingInfo": "No camping, day use only",
    "image": "dishpan-springs.jpg",
    "rating": 4.9,
    "reviews": 67,
    "onxSlug": "dishpan-springs" // Verified
  },
  {
    "id": 8,
    "name": "Ocotillo Wells",
    "location": "Ocotillo Wells, CA",
    "county": "San Diego",
    "difficulty": "beginner",
    "type": "desert",
    "distance": "Unlimited",
    "duration": "Variable",
    "description": "Massive OHV area with dunes, washes, and desert terrain.",
    "coordinates": { "lat": 33.1436, "lng": -116.1331 },
    "camping": true,
    "campingInfo": "Dispersed camping throughout",
    "image": "ocotillo-wells.jpg",
    "rating": 4.5,
    "reviews": 178,
    "onxSlug": "ocotillo-wells-svra" // Verified
  },
  {
    "id": 12,
    "name": "Coxey Road",
    "location": "Joshua Tree, CA",
    "county": "Riverside",
    "difficulty": "advanced",
    "type": "rock",
    "distance": "7 miles",
    "duration": "4-6 hours",
    "description": "Rocky trail through scenic desert with technical sections.",
    "coordinates": { "lat": 33.9333, "lng": -116.8333 },
    "camping": false,
    "campingInfo": "No camping on trail",
    "image": "coxey-road.jpg",
    "rating": 4.4,
    "reviews": 76,
    "onxSlug": "coxey-road" // Verified
  },
  {
    "id": 13,
    "name": "Berdoo Canyon",
    "location": "Indio, CA",
    "county": "Riverside",
    "difficulty": "moderate",
    "type": "canyon",
    "distance": "15 miles",
    "duration": "4-5 hours",
    "description": "Historic canyon trail with scenic desert views into Joshua Tree NP.",
    "coordinates": { "lat": 33.7833, "lng": -116.25 },
    "camping": true,
    "campingInfo": "Primitive camping spots available",
    "image": "berdoo-canyon.jpg",
    "rating": 4.5,
    "reviews": 103,
    "onxSlug": "berdoo-canyon" // Verified
  },
  {
    "id": 17,
    "name": "Thomas Mountain",
    "location": "Garner Valley, CA",
    "county": "Riverside",
    "difficulty": "advanced",
    "type": "mountain",
    "distance": "11 miles",
    "duration": "5-7 hours",
    "description": "Challenging mountain ascent with views of Garner Valley and Lake Hemet.",
    "coordinates": { "lat": 33.6833, "lng": -116.6333 },
    "camping": true,
    "campingInfo": "Primitive camping at various spots",
    "image": "thomas-mountain.jpg",
    "rating": 4.5,
    "reviews": 91,
    "onxSlug": "6s13-thomas-mountain-road" // Verified
  },
  {
    "id": 18,
    "name": "San Jacinto Ridge", // Renamed from "Peak" as the peak is hiking-only
    "location": "Idyllwild, CA",
    "county": "Riverside",
    "difficulty": "moderate",
    "type": "mountain",
    "distance": "16 miles",
    "duration": "4-6 hours",
    "description": "Scenic ridge trail known locally as Bee Canyon. Stunning mountain vistas.",
    "coordinates": { "lat": 33.8147, "lng": -116.6794 },
    "camping": false,
    "image": "san-jacinto.jpg",
    "rating": 4.9,
    "reviews": 45,
    "onxSlug": "san-jacinto-ridge-trail-fs-5s09" // Verified
  },
  {
    "id": 19,
    "name": "Mojave Road",
    "location": "Mojave Desert, CA",
    "county": "San Bernardino",
    "difficulty": "moderate",
    "type": "desert",
    "distance": "147 miles",
    "duration": "2-3 days",
    "description": "Historic pioneer route across the Mojave Desert. Multi-day adventure.",
    "coordinates": { "lat": 35.0125, "lng": -115.6533 },
    "camping": true,
    "campingInfo": "Camp along route",
    "image": "mojave-road.jpg",
    "rating": 4.8,
    "reviews": 287,
    "onxSlug": "mojave-road-central" // Verified: Central is the primary mapped segment
  },
  {
    "id": 24,
    "name": "Cleghorn Ridge",
    "location": "Cajon Pass, CA",
    "county": "San Bernardino",
    "difficulty": "moderate",
    "type": "mountain",
    "distance": "12 miles",
    "duration": "3-5 hours",
    "description": "Scenic ridge trail with beautiful mountain and valley views.",
    "coordinates": { "lat": 34.3167, "lng": -117.4667 },
    "camping": true,
    "onxSlug": "cleghorn-ridge" // Verified
  },
  {
    "id": 26,
    "name": "Pilot Rock",
    "location": "Crestline, CA",
    "county": "San Bernardino",
    "difficulty": "advanced",
    "type": "rock",
    "distance": "4 miles",
    "duration": "3-5 hours",
    "description": "Technical rock trail leading to iconic Pilot Rock formation.",
    "coordinates": { "lat": 34.2333, "lng": -117.3167 },
    "onxSlug": "pilot-rock-ohv" // Verified: Must have "-ohv" to resolve
  },
  {
    "id": 29,
    "name": "Santa Rosa Mountains",
    "location": "La Quinta, CA",
    "county": "Riverside",
    "difficulty": "advanced",
    "type": "mountain",
    "distance": "18 miles",
    "description": "Remote mountain range with challenging trails and spectacular desert-to-mountain transitions.",
    "coordinates": { "lat": 33.5833, "lng": -116.4167 },
    "onxSlug": "santa-rosa-truck-trail-7s02" // Verified
  }
];
